development:
  adapter: postgresql
  database: gemini_development
  pool: 5
  username: tomiwaadewumi
  password: 
 # host: <hostname or ip address. eg.: localhost>

test:
  adapter: postgresql
  database: gemini_test
  pool: 5
  username: tomiwaadewumi
  password: 
 # host: <hostname or ip address. eg.: localhost>
